In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv("./datasets/API_SP.POP.2529.MA.5Y_DS2_en_csv_v2_4901832.csv")

In [9]:
df

,Country Name,Codes,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,6.568037,6.541749,6.560672,6.610868,6.692301,6.794437,...,5.633122,5.768798,5.942144,6.127858,6.275932,6.351372,6.319714,6.162766,5.985740,5.906547
1,Africa Eastern and Southern,AFE,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,7.268827,7.232482,7.193066,7.153990,7.118134,7.085812,...,7.996659,8.029973,8.052314,8.057587,8.031092,7.986239,7.949587,7.918884,7.907558,7.915104
2,Afghanistan,AFG,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,7.869995,7.842659,7.826143,7.814116,7.793515,7.760384,...,6.908638,7.049158,7.237195,7.381759,7.479142,7.614849,7.754925,7.900946,8.072640,8.206038
3,Africa Western and Central,AFW,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,7.589850,7.563194,7.543786,7.528693,7.510447,7.491884,...,7.676077,7.608481,7.552575,7.512758,7.486850,7.475561,7.473160,7.473495,7.481093,7.497339
4,Angola,AGO,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,8.197999,8.187506,8.110129,8.000272,7.847683,7.660072,...,7.567986,7.602068,7.617446,7.612904,7.597314,7.570522,7.528481,7.479027,7.420453,7.362556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,7.774103,7.608481,7.462207,7.376000,7.338576,7.328098,...,8.651405,8.670017,8.587710,8.566801,8.586995,8.512514,8.385447,8.223867,8.100386,8.037085
262,"Yemen, Rep.",YEM,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,7.695322,7.713647,7.733502,7.748178,7.752027,7.748045,...,8.663099,8.807357,8.932683,9.031882,9.108194,9.168922,9.206194,9.214375,9.186832,9.084586
263,South Africa,ZAF,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,7.085578,7.094744,7.065001,7.051755,7.057766,7.086745,...,10.620485,10.826302,10.991493,11.106720,10.981359,10.659040,10.332643,9.983417,9.660897,9.347147
264,Zambia,ZMB,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,7.043807,7.020749,7.007485,6.997478,6.978038,6.948976,...,8.379294,8.340824,8.296422,8.243564,8.185065,8.133338,8.093667,8.067609,8.055195,8.051027
265,Zimbabwe,ZWE,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,6.590636,6.529023,6.477840,6.441299,6.425723,6.424420,...,8.458839,8.081542,7.697981,7.365558,7.124597,6.992275,6.955311,6.996180,7.097758,7.252737

In [10]:
for k in range(1960, 2022):
    df[str(k)] = df[str(k)].apply( lambda x: round(x,2) )

In [11]:
df

,Country Name,Codes,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,6.57,6.54,6.56,6.61,6.69,6.79,...,5.63,5.77,5.94,6.13,6.28,6.35,6.32,6.16,5.99,5.91
1,Africa Eastern and Southern,AFE,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,7.27,7.23,7.19,7.15,7.12,7.09,...,8.00,8.03,8.05,8.06,8.03,7.99,7.95,7.92,7.91,7.92
2,Afghanistan,AFG,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,7.87,7.84,7.83,7.81,7.79,7.76,...,6.91,7.05,7.24,7.38,7.48,7.61,7.75,7.90,8.07,8.21
3,Africa Western and Central,AFW,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,7.59,7.56,7.54,7.53,7.51,7.49,...,7.68,7.61,7.55,7.51,7.49,7.48,7.47,7.47,7.48,7.50
4,Angola,AGO,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,8.20,8.19,8.11,8.00,7.85,7.66,...,7.57,7.60,7.62,7.61,7.60,7.57,7.53,7.48,7.42,7.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,7.77,7.61,7.46,7.38,7.34,7.33,...,8.65,8.67,8.59,8.57,8.59,8.51,8.39,8.22,8.10,8.04
262,"Yemen, Rep.",YEM,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,7.70,7.71,7.73,7.75,7.75,7.75,...,8.66,8.81,8.93,9.03,9.11,9.17,9.21,9.21,9.19,9.08
263,South Africa,ZAF,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,7.09,7.09,7.07,7.05,7.06,7.09,...,10.62,10.83,10.99,11.11,10.98,10.66,10.33,9.98,9.66,9.35
264,Zambia,ZMB,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,7.04,7.02,7.01,7.00,6.98,6.95,...,8.38,8.34,8.30,8.24,8.19,8.13,8.09,8.07,8.06,8.05
265,Zimbabwe,ZWE,"Population ages 25-29, male (% of male populat...",SP.POP.2529.MA.5Y,6.59,6.53,6.48,6.44,6.43,6.42,...,8.46,8.08,7.70,7.37,7.12,6.99,6.96,7.00,7.10,7.25

In [12]:
df.to_json("percent_male_population_25-29.json")

In [13]:
df = pd.read_csv("./datasets/API_SP.POP.2529.FE.5Y_DS2_en_csv_v2_4903816.csv")

In [14]:
df

,Country Name,Codes,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,7.469350,7.417326,7.330106,7.188939,7.052756,6.973942,...,5.445077,5.439920,5.501535,5.627650,5.782759,5.893940,5.910379,5.802254,5.607245,5.405693
1,Africa Eastern and Southern,AFE,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,7.420602,7.393628,7.363263,7.331737,7.300924,7.271023,...,7.959187,8.011359,8.047211,8.059290,8.043447,8.007268,7.966140,7.924756,7.901527,7.897208
2,Afghanistan,AFG,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,7.543998,7.538917,7.542119,7.542224,7.525596,7.496157,...,6.822633,6.967998,7.162352,7.310218,7.407560,7.551135,7.706338,7.868727,8.056326,8.203374
3,Africa Western and Central,AFW,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,7.595807,7.579797,7.565910,7.551969,7.532204,7.509676,...,7.651595,7.582935,7.525949,7.484264,7.456821,7.443972,7.438468,7.434507,7.437240,7.448002
4,Angola,AGO,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,8.668114,8.718384,8.703847,8.661660,8.579742,8.467653,...,7.529041,7.562557,7.579877,7.578699,7.567164,7.544492,7.506024,7.459672,7.402867,7.345595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,7.737344,7.725605,7.673836,7.581724,7.454624,7.306049,...,8.184817,8.115683,7.944356,7.861714,7.852567,7.765965,7.640788,7.484076,7.372221,7.328572
262,"Yemen, Rep.",YEM,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,7.454073,7.468509,7.491600,7.519475,7.537842,7.545770,...,8.559833,8.719488,8.854326,8.962954,9.049148,9.117468,9.168188,9.194466,9.179129,9.083507
263,South Africa,ZAF,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,6.829669,6.814199,6.769830,6.751839,6.769038,6.827391,...,9.706920,9.908298,10.056924,10.130880,10.035115,9.799472,9.529443,9.236320,8.967063,8.707692
264,Zambia,ZMB,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,7.141263,7.082303,7.020190,6.956850,6.895206,6.837583,...,8.097287,8.087709,8.072510,8.049318,8.019946,7.995109,7.980012,7.975636,7.981045,7.991188
265,Zimbabwe,ZWE,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,6.602859,6.519075,6.441565,6.378988,6.344580,6.333831,...,9.661533,9.326542,8.938382,8.557649,8.225753,7.965160,7.785192,7.677679,7.629858,7.654251

In [15]:
for k in range(1960, 2022):
    df[str(k)] = df[str(k)].apply( lambda x: round(x,2) )

In [16]:
df

,Country Name,Codes,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,7.47,7.42,7.33,7.19,7.05,6.97,...,5.45,5.44,5.50,5.63,5.78,5.89,5.91,5.80,5.61,5.41
1,Africa Eastern and Southern,AFE,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,7.42,7.39,7.36,7.33,7.30,7.27,...,7.96,8.01,8.05,8.06,8.04,8.01,7.97,7.92,7.90,7.90
2,Afghanistan,AFG,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,7.54,7.54,7.54,7.54,7.53,7.50,...,6.82,6.97,7.16,7.31,7.41,7.55,7.71,7.87,8.06,8.20
3,Africa Western and Central,AFW,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,7.60,7.58,7.57,7.55,7.53,7.51,...,7.65,7.58,7.53,7.48,7.46,7.44,7.44,7.43,7.44,7.45
4,Angola,AGO,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,8.67,8.72,8.70,8.66,8.58,8.47,...,7.53,7.56,7.58,7.58,7.57,7.54,7.51,7.46,7.40,7.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,7.74,7.73,7.67,7.58,7.45,7.31,...,8.18,8.12,7.94,7.86,7.85,7.77,7.64,7.48,7.37,7.33
262,"Yemen, Rep.",YEM,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,7.45,7.47,7.49,7.52,7.54,7.55,...,8.56,8.72,8.85,8.96,9.05,9.12,9.17,9.19,9.18,9.08
263,South Africa,ZAF,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,6.83,6.81,6.77,6.75,6.77,6.83,...,9.71,9.91,10.06,10.13,10.04,9.80,9.53,9.24,8.97,8.71
264,Zambia,ZMB,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,7.14,7.08,7.02,6.96,6.90,6.84,...,8.10,8.09,8.07,8.05,8.02,8.00,7.98,7.98,7.98,7.99
265,Zimbabwe,ZWE,"Population ages 25-29, female (% of female pop...",SP.POP.2529.FE.5Y,6.60,6.52,6.44,6.38,6.34,6.33,...,9.66,9.33,8.94,8.56,8.23,7.97,7.79,7.68,7.63,7.65

In [17]:
df.to_json("percent_female_population_25-29.json")